variables:
   GIT_SUBMODULE_STRATEGY: recursive
   ORD_SOUMET_W: "10"
   ORD_SOUMET_C: "1"
   ORD_SOUMET_M: "2G"
   ORD_SOUMET_TMPFS: "1G"

stages:
  - package
  - deploy

before_script:
  # Force color CMake output even when output is not TTY
  - export CLICOLOR_FORCE=true
  - if [[ ${CI_COMMIT_REF_NAME} == "dev" && ${ECCI_PROCESS:0:3} != "dev" && ${ECCI_PROCESS} != "nightly" ]]; then ECCI_PROCESS="dev_${CI_PIPELINE_ID}"; fi
  - SSM=${ECCI_SSM}/`[[ ${ECCI_PROCESS:0:3} != "dev" ]] && echo ${ECCI_PROCESS} || echo staging`

package:all:
   stage: package
   only:
      - master
      - tags
      - dev
      - schedules
   script:
      - set +e
      - source ~/ci-env/latest/profile.sh
      - set -e
      - mkdir build
      - cd build
      - cmake ../ 
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

deploy:staging:
   stage: deploy
   only:
      - master
      - tags
      - dev
      - schedules
   script:
      - ~/ci-admin-bundle/bin/ci-stage-ssm.sh code-tools cmake-rpn "${CI_COMMIT_TAG}" "${ECCI_PROCESS}"
